export const doctors = [
  {name: "Bibi Aremieye", deptName: "Surgeon", id: 1, description: "Neurologists are specialists who treat diseases of the brain and spinal cord, peripheral nerves and muscles. Neurological conditions include epilepsy, stroke, multiple sclerosis (MS) and Parkinson's disease"},
  {name: "Savvy P", deptName: "Maternity", id: 2, description: "Neurologists are specialists who treat diseases of the brain and spinal cord, peripheral nerves and muscles. Neurological conditions include epilepsy, stroke, multiple sclerosis (MS) and Parkinson's disease"},
  {name: "Favour James", deptName: "Gynaecologist", id: 3, description: "Neurologists are specialists who treat diseases of the brain and spinal cord, peripheral nerves and muscles. Neurological conditions include epilepsy, stroke, multiple sclerosis (MS) and Parkinson's disease"},
  {name: "John Smith", deptName: "Neorologist", id: 4, description: "Neurologists are specialists who treat diseases of the brain and spinal cord, peripheral nerves and muscles. Neurological conditions include epilepsy, stroke, multiple sclerosis (MS) and Parkinson's disease"},
  {name: "Katherine Mercy", deptName: "Surgeon", id: 5, description: "Neurologists are specialists who treat diseases of the brain and spinal cord, peripheral nerves and muscles. Neurological conditions include epilepsy, stroke, multiple sclerosis (MS) and Parkinson's disease"},
  {name: "Young Chaplain", deptName: "Surgeon", id: 6, description: "Neurologists are specialists who treat diseases of the brain and spinal cord, peripheral nerves and muscles. Neurological conditions include epilepsy, stroke, multiple sclerosis (MS) and Parkinson's disease"},
  {name: "Goat Pig", deptName: "Surgeon", id: 7, description: "Neurologists are specialists who treat diseases of the brain and spinal cord, peripheral nerves and muscles. Neurological conditions include epilepsy, stroke, multiple sclerosis (MS) and Parkinson's disease"},
  {name: "Omah Lay", deptName: "Surgeon", id: 8, description: "Neurologists are specialists who treat diseases of the brain and spinal cord, peripheral nerves and muscles. Neurological conditions include epilepsy, stroke, multiple sclerosis (MS) and Parkinson's disease"},
]