export const symptoms = [
  "bleeding between periods",
  "frequent and urgent need to urinate, or a burning sensation during urination",
  "abnormal vaginal bleeding",
  "bleeding after menopause",
  "pain or pressure in your pelvis that differs from menstrual cramps",
  "increased vaginal discharge",
  "Sores or lumps in the genital area",
  "Itching, burning, swelling, redness, or soreness in the vaginal area",
  "infertility",
  "kidney disease",
  "renal (kidney) failure",
  "diabetes",
  "kidney stones",
  "lupus",
  "hypertension",
  "epilepsy",
  "Parkinson’s disease",
  "multiple sclerosis",
  "stroke",
  "migraine",
  "high blood pressure",
  "high cholesterol",
  "heart rhythm problems",
  "congestive heart failure"
]